# -*- coding: utf-8 -*-
#
# src/sample_data.py
#

import datetime

__all__ = ('timeAgo', 'TEST_DATA')


def timeAgo(days=0, hours=0):
    return datetime.datetime.now() - datetime.timedelta(days=days, hours=hours)


TEST_DATA = {
    "visits": [{"enter_time": timeAgo(days=7, hours=1),  # admin
                "exit_time": timeAgo(days=7, hours=0),
                "barcode": "100091",
                "status": "Out"},
               {"enter_time": timeAgo(days=7, hours=1),  # Joe
                "exit_time": timeAgo(days=7, hours=0),
                "barcode": "100032",
                "status": "Out"},
               {"enter_time": timeAgo(days=7, hours=2),  # Random (Visitor)
                "exit_time": timeAgo(days=7, hours=0.5),
                "barcode": "202107310001",
                "status": "Out"},
               {"enter_time": timeAgo(hours=1),  # admin
                "barcode": "100091",
                "status": "In"},
               {"enter_time": timeAgo(hours=1),  # Random (Visitor)
                "barcode": "202107310001",
                "status": "In"},
               {"enter_time": timeAgo(hours=1),  # Joe
                "barcode": "100032",
                "status": "In"},
               {"enter_time": timeAgo(hours=1),  # Paul
                "barcode": "100015",
                "status": "In"},
               {"enter_time": timeAgo(days=32),  # Artie (Visitor)
                "barcode": "202107310002",
                "status": "Out"}],
    "members": [{"barcode": "100090",
                 "displayName": "Daughter N",
                 "firstName": "Daughter",
                 "lastName": "Name",
                 "email": "fake0@email.com",
                 "membershipExpires": timeAgo(days=-30)},
                {"barcode": "100091",  # user: admin
                 "displayName": "Member N",
                 "firstName": "Member",
                 "lastName": "Name",
                 "email": "fake1@email.com",
                 "membershipExpires": timeAgo(days=-30)},
                {"barcode": "100032",  # user: Joe
                 "displayName": "Average J",
                 "firstName": "Average",
                 "lastName": "Joe",
                 "email": "fake2@email.com",
                 "membershipExpires": timeAgo(days=-30)},
                {"barcode": "100093",
                 "displayName": "Fred N",
                 "firstName": "Fred",
                 "lastName": "Name",
                 "email": "fakeFreddie@email.com",
                 "membershipExpires": timeAgo(days=-30)},
                {"barcode": "100015",
                 "displayName": "Paul F",
                 "firstName": "Paul",
                 "lastName": "Flintstone",
                 "email": "fakePaul@email.com",
                 "membershipExpires": timeAgo(days=-30)}],
    "accounts": [{"user": "admin",
                  "password": "password",
                  "barcode": "100091",
                  "role": 0xFF},
                 {"user": "Joe",
                  "password": "password",
                  "barcode": "100032",
                  "role": 0x40},
                 {"user": "Paul",
                  "password": "password",
                  "barcode": "100015",
                  "role": 0x10}],
    "teams": [{"team_id": 1,
               "program_name": "TFI",
               "program_number": 100,
               "team_name": "Crazy Contraptions",
               "start_date": datetime.datetime(year=2021, month=5, day=1),
               "active": 1},
              {"team_id": 2,
               "program_name": "TFI",
               "program_number": 100,
               "team_name": "Crazy Contraptions",
               "start_date": datetime.datetime(year=2020, month=5, day=1),
               "active": 1},
              {"team_id": 3,
               "program_name": "TFI",
               "program_number": 400,
               "team_name": "Inactive team",
               "start_date": datetime.datetime(year=2020, month=5, day=1),
               "active": 0}],
    "team_members": [{"team_id": 1,
                      "barcode": "100091",
                      "type": 2},
                     {"team_id": 1,
                      "barcode": "100032",
                      "type": 0},
                     {"team_id": 1,
                      "barcode": "100015",
                      "type": 2},
                     {"team_id": 2,
                      "barcode": "100091",
                      "type": 2},
                     {"team_id": 2,
                      "barcode": "100032",
                      "type": 0},
                     {"team_id": 3,
                      "barcode": "100091",
                      "type": 2},
                     {"team_id": 3,
                      "barcode": "100032",
                      "type": 0}],
    "certifications": [{"user_id": "100091",
                        "tool_id": 1,
                        "certifier_id": "LEGACY",
                        "date": "",
                        "level": 30},
                       {"user_id": "100091",
                        "tool_id": 1,
                        "certifier_id": "LEGACY",
                        "date": timeAgo(days=8),
                        "level": 40},
                       {"user_id": "100032",
                        "tool_id": 1,
                        "certifier_id": "100091",
                        "date": timeAgo(days=10),
                        "level": 10}],
    "customReports": [{"report_id": 1,
                       "name": "fred",
                       "sql_text": "SELECT * FROM members;"}],
    "logEvents": [{"what": "Bulk Add",
                   "barcode": "100091",
                   "date": timeAgo(hours=1)}],
    "unlocks": [{"time": timeAgo(hours=1),
                 "location": "TFI",
                 "barcode": "100091"}],
    "guests": [{"guest_id": "202107310001",
                "displayName": "Random G",
                "email": "spam1@email.com",
                "firstName": "Random",
                "lastName": "Guest",
                "whereFound": "invited",
                "status": 1,
                "newsletter": 1},
               {"guest_id": "202107310002",
                "displayName": "Artie N",
                "email": "spam2@email.com",
                "firstName": "Artie",
                "lastName": "Nobody",
                "whereFound": "invited",
                "status": 1,
                "newsletter": 0}],
    "devices": [{"mac": "87:65:43:21:00:54",
                 "barcode": "100091",
                 "name": "Phone"}],
    "config": [{"key": "grace_period",
                "value": "15"}]
    }
